FROM ubuntu:22.04

COPY src/* /root/

ENV BAKS3S3_TIMEZONE="Europe/London"
ENV BAKS3S3_CRON_TIME=""
ENV BAKS3S3_SRC_BUCKET=""
ENV BAKS3S3_SRC_DIR=""
ENV BAKS3S3_SRC_ENDPOINT=""
ENV BAKS3S3_SRC_KEY=""
ENV BAKS3S3_SRC_REGION=""
ENV BAKS3S3_SRC_SECRET=""
ENV BAKS3S3_TARGET_BUCKET=""
ENV BAKS3S3_TARGET_DIR=""
ENV BAKS3S3_TARGET_ENDPOINT=""
ENV BAKS3S3_TARGET_KEY=""
ENV BAKS3S3_TARGET_REGION=""
ENV BAKS3S3_TARGET_SECRET=""

RUN chmod 755 /root/*.sh && \
	 /root/install.sh

CMD ["/root/run.sh"]
